version: '2'

services:
  myapp:
    image: 'bitnami/symfony:1'
    ports:
      - '8000:8000'
    volumes:
      - './:/app'
    environment:
      - SYMFONY_PROJECT_NAME=myapp
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=test
      - MARIADB_PASSWORD=1234
      - MARIADB_DATABASE=database
      - COMPOSER_MEMORY_LIMIT=-1
    depends_on:
      - mariadb
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=test
      - MARIADB_PASSWORD=1234
      - MARIADB_DATABASE=database
    ports:
      - '3320:3306'