security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
        api:
            pattern: ^/api
            stateless: true
            security: true
            guard:
                authenticators:
                    - App\Security\JwtAuthenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles:  IS_AUTHENTICATED_FULLY}