controllers:
    resource: ../../src/Controller
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

api:
    prefix: /api
    resource: /app/myapp/src/Controller/Api

